/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TokenTreePanel.java
 *
 * Created on 27.10.2009, 13:06:35
 */
package org.myjaphoo.gui.token;

import org.myjaphoo.gui.panel.AbstractEmbeddablePanel;
import org.myjaphoo.gui.util.WrappedNode;
import org.myjaphoo.model.db.Token;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ResourceBundle;

/**
 *
 * @author mla
 */
public class TokenPanel extends AbstractEmbeddablePanel {

    private final static ResourceBundle localeBundle = ResourceBundle.getBundle("org/myjaphoo/gui/token/resources/TokenPanel");

    public static final Logger LOGGER = LoggerFactory.getLogger(TokenPanel.class.getName());
    private TokenPanelController controller;

    /** Creates new form TokenTreePanel */
    public TokenPanel(TokenPanelController controller) {
        this.controller = controller;
        initComponents();
        ((TokenTree) jXTreeTable1).addMouseListener(new TokenTreeMouseListener(controller, (TokenTree) jXTreeTable1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jCheckBoxFlat = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTreeTable1 = new org.myjaphoo.gui.token.TokenTree(controller);

        setMinimumSize(new java.awt.Dimension(99, 25));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(TokenPanel.class);
        jCheckBoxFlat.setText(resourceMap.getString("jCheckBoxFlat.text")); // NOI18N
        jCheckBoxFlat.setFocusable(false);
        jCheckBoxFlat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBoxFlat.setName("jCheckBoxFlat"); // NOI18N
        jCheckBoxFlat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBoxFlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFlatActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBoxFlat);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jXTreeTable1.setName("jXTreeTable1"); // NOI18N
        jXTreeTable1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jXTreeTable1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jXTreeTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jXTreeTable1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jXTreeTable1ValueChanged
        if (evt.getPath().getLastPathComponent() instanceof WrappedNode) {
            controller.setCurrentToken(((WrappedNode<Token>) evt.getPath().getLastPathComponent()).getRef());
        }

    }//GEN-LAST:event_jXTreeTable1ValueChanged

    private void jCheckBoxFlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFlatActionPerformed
        controller.setFlatView(!controller.isFlatView());
        refreshView();
    }//GEN-LAST:event_jCheckBoxFlatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxFlat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTreeTable jXTreeTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return localeBundle.getString("TOKENS");
    }

    @Override
    public void refreshView() {
        ((TokenTree) jXTreeTable1).refreshTree();
        
    }

    @Override
    public void clearView() {
        jXTreeTable1.setTreeTableModel(new TokenTreeModel(null, true));
    }

    public void setShowPreviewBigMode() {
        ((TokenTree) jXTreeTable1).setShowPreviewBigMode();
    }
}
