/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemoveElements.java
 *
 * Created on 23.12.2009, 11:19:10
 */

package org.myjaphoo.gui.removeElementsDialog;

import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;
import org.jdesktop.swingx.JXCheckList;
import org.myjaphoo.gui.Commons;

/**
 *
 * @author mla
 */
public class RemoveElementsDialog<T> extends javax.swing.JDialog {

    private List<T> elements2ChooseFrom;
    private boolean ok = false;

    /** Creates new form RemoveTokenDialog */
    public RemoveElementsDialog(java.awt.Frame parent, String headerTitle, String sideText, final List<T> elements2ChooseFrom) {
        super(parent, true);
        this.elements2ChooseFrom = elements2ChooseFrom;
        initComponents();
        getChkList().setModel(new AbstractListModel() {

            @Override
            public int getSize() {
                return elements2ChooseFrom.size();
            }

            @Override
            public Object getElementAt(int index) {
                return elements2ChooseFrom.get(index);
            }
        });
        getChkList().setRolloverEnabled(true);
        getChkList().addHighlighter(Commons.ROLLOVER_ROW_HIGHLIGHTER);
        jXHeader1.setTitle(headerTitle);
        jXHeader2.setTitle(sideText);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXHeader2 = new org.jdesktop.swingx.JXHeader();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXCheckList();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jXHeader1.setName("jXHeader1"); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(RemoveElementsDialog.class);
        jXHeader1.setTitle(resourceMap.getString("jXHeader1.title")); // NOI18N
        getContentPane().add(jXHeader1, java.awt.BorderLayout.NORTH);

        jXPanel1.setName("jXPanel1"); // NOI18N
        jXPanel1.setLayout(new java.awt.BorderLayout());

        jXHeader2.setName("jXHeader2"); // NOI18N
        jXHeader2.setTitle(resourceMap.getString("jXHeader2.title")); // NOI18N
        jXPanel1.add(jXHeader2, java.awt.BorderLayout.WEST);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jXList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jXList1.setName("jXList1"); // NOI18N
        jScrollPane1.setViewportView(jXList1);

        jXPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jXPanel1, java.awt.BorderLayout.CENTER);

        jXPanel2.setName("jXPanel2"); // NOI18N

        jButtonOk.setText(resourceMap.getString("jButtonOk.text")); // NOI18N
        jButtonOk.setName("jButtonOk"); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jXPanel2.add(jButtonOk);

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jXPanel2.add(jButtonCancel);

        getContentPane().add(jXPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        ok=true;
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        ok=false;
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    private org.jdesktop.swingx.JXHeader jXHeader2;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    // End of variables declaration//GEN-END:variables

    private JXCheckList getChkList() {
        return (JXCheckList) jXList1;
    }


    public boolean isOk() {
        return ok;
    }

    public List<T> getCheckedElements() {
        boolean[] checked = getChkList().getChecked();
        ArrayList<T> checkedElements = new ArrayList<T>();
        for (int i = 0; i< checked.length; i++) {
            if (checked[i]) {
                checkedElements.add(elements2ChooseFrom.get(i));
            }
        }
        return checkedElements;
    }
}
