/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TokenTreePanel.java
 *
 * Created on 27.10.2009, 13:06:35
 */
package org.myjaphoo.gui.metaToken;

import org.myjaphoo.gui.panel.AbstractEmbeddablePanel;
import org.myjaphoo.gui.util.WrappedNode;
import org.myjaphoo.model.db.MetaToken;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author mla
 */
public class MetaTokenPanel extends AbstractEmbeddablePanel {

    public static final Logger LOGGER = LoggerFactory.getLogger(MetaTokenPanel.class.getName());
    private MetaTokenPanelController controller;

    /** Creates new form TokenTreePanel */
    public MetaTokenPanel(MetaTokenPanelController controller) {
        this.controller = controller;
        initComponents();
        ((MetaTokenTree) jXTreeTable1).addMouseListener(new MetaTokenTreeMouseListener(controller, (MetaTokenTree) jXTreeTable1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTreeTable1 = new org.myjaphoo.gui.metaToken.MetaTokenTree(controller);

        setMinimumSize(new java.awt.Dimension(99, 25));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(MetaTokenPanel.class);
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox1);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jXTreeTable1.setName("jXTreeTable1"); // NOI18N
        jXTreeTable1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jXTreeTable1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jXTreeTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jXTreeTable1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jXTreeTable1ValueChanged

        if (evt.getPath().getLastPathComponent() instanceof WrappedNode) {
            MetaToken mt = ((WrappedNode<MetaToken>) evt.getPath().getLastPathComponent()).getRef();
            controller.setCurrentMetaToken(mt);
        }
    }//GEN-LAST:event_jXTreeTable1ValueChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        controller.setFlatView(!controller.isFlatView());
        refreshView();
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTreeTable jXTreeTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "MetaTokens"; //NOI18N
    }

    @Override
    public void refreshView() {
        ((MetaTokenTree) jXTreeTable1).refreshTree();
    }

    @Override
    public void clearView() {
        jXTreeTable1.setTreeTableModel(new MetaTokenTreeModel(null, true));
    }

    public void setShowPreviewBigMode() {
        ((MetaTokenTree) jXTreeTable1).setShowPreviewBigMode();
    }
}
