/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TextViewer.java
 *
 * Created on 07.04.2010, 17:05:01
 */

package org.myjaphoo.gui.textviewer;

import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;

/**
 *
 * @author mla
 */
public class TextViewer extends javax.swing.JFrame {

    /** Creates new form TextViewer */
    public TextViewer(String filename) {
        initComponents();
        loadFile(filename);
        setTitle(filename);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHeader1 = new org.jdesktop.swingx.JXHeader();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Form"); // NOI18N

        jXHeader1.setName("jXHeader1"); // NOI18N
        getContentPane().add(jXHeader1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private org.jdesktop.swingx.JXHeader jXHeader1;
    // End of variables declaration//GEN-END:variables

    private void loadFile(String filename) {
        try {
            String content = org.apache.commons.io.FileUtils.readFileToString(new File(filename));
            jTextPane1.setText(content);
        } catch (IOException ex) {
            LoggerFactory.getLogger(TextViewer.class.getName()).error("error", ex); //NOI18N
        }
    }

}
