/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TokenTreePanel.java
 *
 * Created on 27.10.2009, 13:06:35
 */
package org.myjaphoo.gui.changelog;

import org.myjaphoo.MyjaphooController;
import org.myjaphoo.gui.panel.AbstractEmbeddablePanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author mla
 */
public class ChangeLogPanel extends AbstractEmbeddablePanel {

    public static final Logger LOGGER = LoggerFactory.getLogger(ChangeLogPanel.class.getName());
    private MyjaphooController controller;

    /** Creates new form TokenTreePanel */
    public ChangeLogPanel(MyjaphooController controller) {
        this.controller = controller;
        initComponents();
        ((ChangeLogTable) jXTable2).refreshModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar3 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTable2 = new org.myjaphoo.gui.changelog.ChangeLogTable(controller);

        setMinimumSize(new java.awt.Dimension(99, 25));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jToolBar3.setRollover(true);
        jToolBar3.setName("jToolBar3"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(ChangeLogPanel.class);
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton2);

        add(jToolBar3, java.awt.BorderLayout.NORTH);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable2.setName("jXTable2"); // NOI18N
        jScrollPane3.setViewportView(jXTable2);

        add(jScrollPane3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ((ChangeLogTable) jXTable2).refreshModel();
    }//GEN-LAST:event_jButton2ActionPerformed


 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar3;
    private org.jdesktop.swingx.JXTable jXTable2;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "ChangeLog";
    }

    @Override
    public void refreshView() {
    }

    @Override
    public void clearView() {
    }
}
