/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MessageView.java
 *
 * Created on 09.01.2012, 18:28:49
 */
package org.myjaphoo.gui.messages;

/**
 *
 * @author mla
 */
public class MessagePanel extends javax.swing.JPanel {

    /** Creates new form MessageView */
    public MessagePanel() {
        initComponents();
        jXTreeTable1.setTreeTableModel(new MessageTreeModel(new MessageTreeNode()));
        jXTreeTable1.setTreeCellRenderer(new MessageRenderer());
        jXTreeTable1.getColumn(1).setCellRenderer(new ProgressCellRenderer());
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTreeTable1 = new org.jdesktop.swingx.JXTreeTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(MessagePanel.class);
        jButtonClear.setText(resourceMap.getString("jButtonClear.text")); // NOI18N
        jButtonClear.setFocusable(false);
        jButtonClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonClear.setName("jButtonClear"); // NOI18N
        jButtonClear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonClear);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jXTreeTable1.setName("jXTreeTable1"); // NOI18N
        jScrollPane1.setViewportView(jXTreeTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jXTreeTable1.setTreeTableModel(new MessageTreeModel(new MessageTreeNode()));
        jXTreeTable1.setTreeCellRenderer(new MessageRenderer());
        jXTreeTable1.getColumn(1).setCellRenderer(new ProgressCellRenderer());
    }//GEN-LAST:event_jButtonClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.swingx.JXTreeTable jXTreeTable1;
    // End of variables declaration//GEN-END:variables
}
