/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MovieSelectionConfirmationDialog.java
 *
 * Created on 21.09.2009, 16:09:37
 */
package org.myjaphoo.gui.sellists;

import org.myjaphoo.MovieNode;
import org.myjaphoo.gui.thumbtable.ThumbPanelController;
import org.myjaphoo.model.db.MovieEntry;

import java.awt.*;
import java.util.Collection;
import java.util.List;

/**
 *
 * @author mla
 */
public class MovieSelectionConfirmationDialog extends javax.swing.JDialog {

    private boolean ok = false;
    private ThumbPanelController controller;

    /** Creates new form MovieSelectionConfirmationDialog */
    public MovieSelectionConfirmationDialog(String title, java.awt.Frame parent, List<MovieEntry> entryList) {
        super(parent, true);
        controller = new SelectionDisplayThumbController(entryList);
        setPreferredSize(new Dimension(900, 600));
        initComponents();
        this.setTitle(title);
        this.jXTitledPanel1.setTitle(title);
    }

    /** Creates new form MovieSelectionConfirmationDialog */
    public MovieSelectionConfirmationDialog(String title, java.awt.Frame parent, Collection<MovieNode> entryList) {
        super(parent, true);
        controller = new SelectionDisplayThumbController(entryList);
        setPreferredSize(new Dimension(900, 600));
        initComponents();
        this.setTitle(title);
        this.jXTitledPanel1.setTitle(title);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thumbPanel = new org.myjaphoo.gui.thumbtable.ThumbPanel(controller);
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        thumbPanel.setName("thumbPanel"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jXTitledPanel1.setContentContainer(thumbPanel);
        jXTitledPanel1.setName("jXTitledPanel1"); // NOI18N
        getContentPane().add(jXTitledPanel1, java.awt.BorderLayout.CENTER);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(MovieSelectionConfirmationDialog.class);
        jButtonOk.setText(resourceMap.getString("jButtonOk.text")); // NOI18N
        jButtonOk.setName("jButtonOk"); // NOI18N
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOk);

        jButtonCancel.setText(resourceMap.getString("jButtonCancel.text")); // NOI18N
        jButtonCancel.setName("jButtonCancel"); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancel);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        ok = true;
        setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        ok = false;
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JPanel thumbPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ok
     */
    public boolean isOk() {
        return ok;
    }
}
