/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TokenTreePanel.java
 *
 * Created on 27.10.2009, 13:06:35
 */
package org.myjaphoo.gui.db;

import org.mlsoft.swing.jtable.MappedTableModel;
import org.myjaphoo.MyjaphooController;
import org.myjaphoo.gui.panel.AbstractEmbeddablePanel;
import org.myjaphoo.model.dbconfig.DatabaseConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ResourceBundle;

/**
 *
 * @author lang
 */
public class DatabaseConnectionPanel extends AbstractEmbeddablePanel {

    private final static ResourceBundle localeBundle = ResourceBundle.getBundle("org/myjaphoo/gui/db/resources/DatabaseConnectionPanel");
    public static final Logger LOGGER = LoggerFactory.getLogger(DatabaseConnectionPanel.class.getName());
    private MyjaphooController controller;
    private DatabaseConnectionController dbController;

    /** Creates new form TokenTreePanel */
    public DatabaseConnectionPanel(MyjaphooController controller) {
        this.controller = controller;
        dbController = new DatabaseConnectionController(controller);
        initComponents();
        ((DatabaseConnectionTable) jXTable1).refreshModel();
    }

    private DatabaseConfiguration getSelectedConfiguration() {
        int[] selrow = org.myjaphoo.gui.util.Tables.getModelSelectedRowsForJXTable(jXTable1);
        int firstSel = selrow[0];
        MappedTableModel<DatabaseConfiguration> model = (MappedTableModel<DatabaseConfiguration>) jXTable1.getModel();
        DatabaseConfiguration dbconfig = model.get(firstSel);
        return dbconfig;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonDelete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonExportToDatabase = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.myjaphoo.gui.db.DatabaseConnectionTable(dbController);

        setMinimumSize(new java.awt.Dimension(99, 25));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);
        jToolBar2.setName("jToolBar2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.myjaphoo.MyjaphooApp.class).getContext().getResourceMap(DatabaseConnectionPanel.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        jButtonNew.setText(resourceMap.getString("jButtonNew.text")); // NOI18N
        jButtonNew.setFocusable(false);
        jButtonNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNew.setName("jButtonNew"); // NOI18N
        jButtonNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonNew);

        jButtonEdit.setText(resourceMap.getString("jButtonEdit.text")); // NOI18N
        jButtonEdit.setFocusable(false);
        jButtonEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdit.setName("jButtonEdit"); // NOI18N
        jButtonEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonEdit);

        jSeparator1.setName("jSeparator1"); // NOI18N
        jToolBar2.add(jSeparator1);

        jButtonDelete.setText(resourceMap.getString("jButtonDelete.text")); // NOI18N
        jButtonDelete.setFocusable(false);
        jButtonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDelete.setName("jButtonDelete"); // NOI18N
        jButtonDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonDelete);

        jSeparator2.setName("jSeparator2"); // NOI18N
        jToolBar2.add(jSeparator2);

        jButtonExportToDatabase.setText(resourceMap.getString("jButtonExportToDatabase.text")); // NOI18N
        jButtonExportToDatabase.setFocusable(false);
        jButtonExportToDatabase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExportToDatabase.setName("jButtonExportToDatabase"); // NOI18N
        jButtonExportToDatabase.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExportToDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportToDatabaseActionPerformed(evt);
            }
        });
        jToolBar2.add(jButtonExportToDatabase);

        add(jToolBar2, java.awt.BorderLayout.NORTH);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1.setName("jXTable1"); // NOI18N
        jXTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jXTable1);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jXTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTable1MouseClicked
        if (evt.getClickCount() == 2) {// double click

            int[] selrow = org.myjaphoo.gui.util.Tables.getModelSelectedRowsForJXTable(jXTable1);
            int firstSel = selrow[0];
            MappedTableModel<DatabaseConfiguration> model = (MappedTableModel<DatabaseConfiguration>) jXTable1.getModel();
            /*
            ChronicEntry node = model.getChronic(firstSel);
            controller.getFilter().popChronic(node);
            controller.getView().updateChronic(node);
            controller.getView().updateViews();
             */
        }
    }//GEN-LAST:event_jXTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ((DatabaseConnectionTable) jXTable1).refreshModel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        DatabaseConfiguration newOne = dbController.newDatabaseConnection();
        dbController.edit(newOne);
        ((DatabaseConnectionTable) jXTable1).refreshModel();

    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        DatabaseConfiguration dbconfig = getSelectedConfiguration();
        dbController.edit(dbconfig);
        ((DatabaseConnectionTable) jXTable1).refreshModel();

    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        DatabaseConfiguration dbconfig = getSelectedConfiguration();
        dbController.delete(dbconfig);
        ((DatabaseConnectionTable) jXTable1).refreshModel();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonExportToDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportToDatabaseActionPerformed
        DatabaseConfiguration dbconfig = getSelectedConfiguration();
        dbController.exportToDatabase(dbconfig);
    }//GEN-LAST:event_jButtonExportToDatabaseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonExportToDatabase;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar2;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return localeBundle.getString("DATABASECONNECTIONS");
    }

    @Override
    public void refreshView() {
    }

    @Override
    public void clearView() {
    }
}
